# Generated by Django 4.2.6 on 2023-11-06 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 15, 50, 49, 767349)),
        ),
    ]
