# Generated by Django 4.2.6 on 2023-11-06 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_listing', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 17, 38, 2, 53445, tzinfo=datetime.timezone.utc)),
        ),
    ]
