# Generated by Django 4.2.6 on 2023-11-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 18, 41, 38, 393981, tzinfo=datetime.timezone.utc)),
        ),
    ]
